### ISSUE TITLE
Utvikle støtte for tilgangsstyring til enkeltinstanser av en 3.0 app/ressurs

### ISSUE THREAD

**Issue by GGunnar** [Altinn/altinn-authorization#10]
Håndtereres videre i https://github.com/Altinn/altinn-access-management/issues/658

# Overordnet beskrivelse av behov
I Altinn II er det mulig å gi tilgang til et enkeltelement (enkeltinstans) til en annen part. Enkeltelement kan f.eks. være et spesifikt skjema under utfylling, eller et bestemt brev man har mottatt. 

Dette innebærer at en bestemt app-instans kan bli delegert til en bestemt part (enten en sluttbruker eller en organisasjon).

# Overordnet beskrivelse av løsning
Det skal være mulig å dele hele instansen eller enkeltoperasjoner (f.eks Lese eller Signere) i en instans. Dagens A2-løsning er begrenset til instanser som ligger i innboksen i Altinn, men i Altinn 3.0 er det ønskelig at funksjonaliteten er tilgjengelig for både apper og ressurser i ressursregisteret.
Dette arbeidet henger sammen med utredning som gjøres av Team Tilgangsinformasjon (https://github.com/Altinn/altinn-authentication/issues/219) i forbindelse med [dialogporten](https://digdir.github.io/dialogporten/)

Ønsket funksjonalitet:
- GUI for instansdelegering av elementer som ligger I Altinn (bør gjøres fra innboksen) 
- GUI for visning av hvilke instansdelegeringer som er gjort
    - inkl GUI for å slette/revoke instansdelegering
- API for instansdelegering
- Intansdelegring bør kunne lagres i samme policy som vi i dag har for app-delegeringer, dette kan gi ytelsesproblemer...
    - alternativet er å bygge egne tabeller/filer for instansdelegeringer, antagelig er det det vi trenger...
 

Må avklare hvilken datamodell for å lagre instansdelegeringer. Trenger antagelig egen databasetabell for å holde instansdelegeringer
Ligger antagelig i egne policyfiler
GUI - hvor detaljert skal tilgangsstyring på delegering være? På skjemainstans kan du i dag skille på ulike instanser. På correspondence så får du alt. Antagelig blir dette likt som for delegering på ressursnivå

## Mulig utvidelse
- Eksterne instanser må ha et eget gui for delegring av instanser. Delegeringer må sendes til Altinn via API med tilstrekkelig informasjon til at vi kan vise frem instansdelegeringen i GUI

# Dagens løsning
## Melding/correspondence

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/c15f92cd-0add-4251-8be5-fb22c99f142b)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/45c9d3a1-92c0-4e7f-a447-b7e100344b0e)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/9108cee6-fda5-4be7-8093-4775c3792d50)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/e81f9c49-9adf-45ce-95c5-e8b090a67078)
Meldinger/coorespondence er det bare  mulig å dele "alt".

## Skjema

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/39c039cb-0f84-4edb-a195-3ed7342825d9)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/c98eff32-0a9f-4535-b200-e2d78b2b051c)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/26e43e48-8eec-4f09-9d32-2e07cd7b20bf)

Kan redigere hvilke operasjoner som skal deles:
![image](https://github.com/Altinn/altinn-authorization/assets/36295493/a1eaffa0-9d40-4472-aa38-6824121db78f)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/f226fa62-dce6-4ae3-b795-c32b36fba37b)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/191d07ba-fc16-4272-9dd0-f383258acc2b)

![image](https://github.com/Altinn/altinn-authorization/assets/36295493/7b2c89f8-b7eb-4d2b-ba65-f772c0f61221)

**Comment by rtafj** [comment]
Funksjonell refinement 18/3:
I første omgang vil instansdelegering kunne skille mellom lese-tilgang og tilgang til alt på instansen.

**Comment by annerisbakk** [comment]
Håndtereres videre i https://github.com/Altinn/altinn-access-management/issues/658
