### ISSUE TITLE
Tilby autorisasjon for Events i 3.0

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#107]
### Overordnet beskrivelse av behov
Altinn Autorisasjon skal benyttes som autorisasjonsløsning for å styre hvem som kan publisere og lese hendelser som publiseres på Altinn Events komponenten, se https://docs.altinn.studio/technology/architecture/capabilities/runtime/integration/events/ 
 
### Spørsmål

**Comment by ekorra** [comment]
Duplicate of https://github.com/orgs/Altinn/projects/75/views/3?filterQuery=label%3AEpic%2Cepic&pane=issue&itemId=22747809
