### ISSUE TITLE
Migreringsstrategi for lenketjenester

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#108]
Følgende spørsmål må avklares

1. skal lenketjeneser migreres èn og èn eller skal alle migreres i en operasjon?
2. skal Digdir ta ansvar for å registrere all informasjon om lenketjenestene i ressursregisteret eller skal vi lese inn "det vi finner" i Altinn 2 og be tjenesteeiere oppdatere informasjon selv før produksjonssetting?
3. skal vi la tjenesteeier produksjonssette selv?

Foreløpig konklusjon sprm 1  **«Vi trenger en løsning som støtter at alle lenketjenester IKKE migreres på en gang, men flyttes en og en.»**

Begrunnelse: Vi må sikre en «mellom-løsning» som sørger for at tjenester migreres over til A3 så raskt som mulig uten for store tap av Autorisasjons-funksjonalitet. Det er meget sannsynlig at f eks formidlingstjeneste og meldingstjeneste er migrert over til A3 før nye tilgangsgrupper og NØTT innføres. Vi bør derfor bruke innfasing av Lenketjenester til å finne denne «mellomløsningen». 

Foreløpig konklusjon sprm  2: **Vi ønsker at tjenesteeier selv skal fylle ut manglende informasjon om ressursen og sette den "klar til migrering"**

Foreløpig konklusjon sprm  3: **Nei, tjenesteeier skal klargjøre tjeneste for migrering (manglende tekster) og selv aktivt sette tjenesten klar til migrering. Selve migrering av tjeneste og tilhørende representasjonsforhold utføres av Devopsteamet. Teamets prosess bør "halv-automatiseres" ettersom det er 300 tjenester det gjelder (lage script som kan gjenbrukes enkelt).**

******************************

Situasjonen vil være som følger når vi starter utvikling: 
![image.png](https://images.zenhubusercontent.com/60fe9998c772df87619e16fb/95b388b2-e5b8-4a02-b089-8243183e83a0)

Orange bokser ligger i A3. Blå bokser ligger i A2. 

1. Alle roller er definert i A2 
2. A2 inneholder informasjon om hvem som har hvilke ER-roller
3. A2 inneholder informasjon om hvem som har fått delegert hvilke A2-roller
4. Delegeringer av Delegerbare API ligger i A3
5. Delegeringer på A3 apps ligger i A3 
6. Det finnes info i A2 «om» at noe er delegert i forbindelse med denne appen 
7. Delegeringer av øvrige tjenester (A2 skjema, melding, formidling)  ligger i A2
8. Øvrige tjenester (skjema, melding, formidling) ligger i A2
     a.	Det ligger også en «placeholder» for alle Altinn 3 apps i Altinn servicecatalogue
     b.	Policy for A2 tjenester ligger i A2. Disse henviser til A2 roller og ER roller
      c.	SRR regler for A2 tjenester ligger i A2
9.	3.0 apps er registert som APP i A3 
     a.	Policy for 3.0 apps ligger i A3. Disse henviser til A2 roller og ER roller
10.	Delegerbare API ressurser (og etter hvert lenketjenester) ligger som Ressurser i A3
     a.	Policy for Delegerbare API ressurser ligger som regel i A3
     b.	RRR regler for A3 ressurser vil ligge i A3

*********************
**In scope for å realisere lenketjenestemigrering:** 

1. Tilby GUI for å registrere og oppdatere A3 ressurser i Ressursregister inkl policyregler Altinn/altinn-resource-registry#78
2. Tilby funksjonalitet for å registrere DelegationRequest i A3 for A3 ressurser.  https://github.com/Altinn/altinn-access-management/issues/332
3. Tilby funskjonalitet for å registrere ResourceownerRightRegister på ressurser i A3. https://github.com/Altinn/altinn-resource-registry/issues/131
4. Nødvendige endringer i GUI for å støtte migrering av lenketjenester èn og èn til A3 Altinn/altinn-authorization#142
           a) Inkl å forbedre søkevindu for å finne tjenester (delegering og delegationrequest). Filter for tjenesteeier, sortere bort SRR/RRR tjenester, søk i tittel, rettighetsbeskrivlese
6. Nødvendige endringer i API for å støtte migrering av lenketjenester èn og èn til A3 Altinn/altinn-authorization#143
7. Avskaffe lokale roller i A2. Evt vurdere behovet på nytt etter at Nøtt og nye tilgangsgrupper er lansert. Altinn/altinn-authorization#144

 **Må vurderes:** 

1. Endre App i A3 slik at de blir Resources? – vil gjøre det enklere å registrere regler knyttet til Apps?
PS: dette spørsmålet må sees opp i mot løsningsbeskrivelse for Dialogporten og hvordan Apper skal kobles til denne. Kan være hensiktsmessig å utsette dette til senere for å spare arbeid med endringer i Studio? 
Følges opp i denne epic: https://github.com/Altinn/altinn-resource-registry/issues/160

**Comment by jonkjetiloye** [comment]
@TheTechArch 
Jeg sliter litt med å se hvordan vi skal levere 1 uten og også samkjøre behandlingen i 2. slik at app delegering og andre ressursregister delegeringer håndteres likt. 

Det vil vel fort bli kaos og forvirring både teknisk/implementasjonsmessig og potensielt i APIer og integrasjoner og Policy-er dersom vi skal måtte vedlikeholde å "trikse" frem og tilbake mellom Org/App referanser og RessursId referanser.
