### ISSUE TITLE
Delegation of Altinn-app to another party (end-user)

### ISSUE THREAD

**Issue by GGunnar** [Altinn/altinn-authorization#11]
## Description
In Altinn 2 it is possible to delegate an app (called service) from one party to another party/user. 

It is therefore expected that there is a need for this for Altinn 3 as well, meaning a party could get a delegation to work on that specific Altinn-app. 

The functional reason for not just delegate the needed roles is that roles typically gives access to many apps.

**Comment by altinnadmin** [comment]
@sivaglen @TheTechArch Denne kan vel lukkes?

**Comment by sivaglen** [comment]
Dette testes i produksjon i morgen. Hvis alt ok så slås feature på.
