### ISSUE TITLE
Analyse - hva gjør vi med API (SBS, TE) i A2 for å støtte migrering av lenketjenester til A3?

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#143]
Vi må kartlegge hvilke API som påvirkes av at lenketjenester flyttes, undersøke bruken av disse og velge strategi for hver tjeneste

## SBS: 
  - REST: https://www.altinn.no/api/help/
  - SOAP: https://altinn.github.io/docs/api/soap/endepunkter-oversikt/
Foreløpig konklusjon: 
- Det tilbys ikke proxy for SOAP-grensesnitt
- Det er kun REST-api i A2 som vi evt trenger å lage proxy for. 
![Image](https://user-images.githubusercontent.com/25847572/220101887-606f148c-703e-48c6-830d-5eda4fd24400.png)

Oversikt over brukere av SluttbrukersysteAPI ligger her (krever tilgang): 
https://digdir.sharepoint.com/:w:/r/sites/Autorisasjonogformidling/Delte%20dokumenter/General/Transformasjon%202.0%20-%203.0/Veien%20videre%20for%20autorisasjonsAPI%20i%20A2/Brukere%20av%20API%20relevant%20for%20migrering%20av%20lenketjenester.docx?d=we8a3a9bd0d2b4b90a3b3a257c6365459&csf=1&web=1&e=E31okG
 
## Tjenesteeiere
  - REST: https://www.altinn.no/api/serviceowner/help
  - SOAP: https://altinn.github.io/docs/api/tjenesteeiere/soap/grensesnitt/
  - Tjenesteeier bestemmer selv når de migrerer lenketjenester. De kan derfor vente med å migrere til de er klar til å ta i bruk nye api. 

Foreløpig konklusjon: 
- Det tilbys ikke proxy for SOAP-grensesnitt
- Bilde nedenfor viser strategi for de ulike tjenestene i Serviceowner REST API
![Image](https://user-images.githubusercontent.com/25847572/220063673-c8b92212-8a31-4857-a3e9-f3e1bbce27be.png)

Oversikt over brukere av ServiceownerAPI ligger her (krever tilgang): 
https://digdir-my.sharepoint.com/:w:/r/personal/siv_therese_aglen_digdir_no/Documents/Tjenesteeiers%20bruk%20av%20REST%20api.docx?d=w17456ef62ea74fcd8d372887b4bc6247&csf=1&web=1&e=vUFufA

Nye API må ha støtte for OIDC autentisering med mulighet for begrensning av hvilken avgiver og hvilke ressurser. 
- [ ] Kan vi gjenbruke samtykker gitt i idPorten i A2 kontekts for å hente ut avigerliste både i A2 og A3 kontekst? 

## Hent Reportees (avgiverliste) 

![image](https://user-images.githubusercontent.com/25847572/205979289-683da0b5-7e4c-48d3-98d1-783c22690577.png)

Må kunne hente delegations for ressurstyper: "lenketjeneester" og "delegerbareAPIressurser" i A3
- [x] vi må definere hvilke ressurstyper vi skal ha i A3 i forhold til kategorisering og gode brukeropplevelser. "Hva er denne ressursen? Skjema, ?, ?" 
Det finnes allerede en avgiverliste i A3 som i dag henter avgiverliste via SBL bridge. 

## Hent Rettigheter (SBS)

![Image](https://user-images.githubusercontent.com/25847572/218726343-3cd2725d-146a-44d5-945b-25d17e6b3183.png)

- I A3 bør vi ikke tilby en tjeneste som lister ut alle rettigheter en bruker har på vegne av en gitt avgiver. 
  - *En slik bruk av tjenesten kan vi ikke tilby en proxy for.*
- Antagelse: de fleste konsumenter spør ikke om alle rettigheter, men bruker ODATA for å filtrere på en gitt servicecode. 
  - *En slik bruk av tjenesten kan vi tilby proyxy for" 
- Vi har 6 konsumenter av GetRights endepunktet. 117 000 oppslag siste 6 mnd, En aktør er svært stor

- [ ] Dialog med alle som bruker denne tjenesten i dag og varsle om endringer som evt kan knekke deres implementasjon 
- [ ] snakk med stor konsument om hvorfor de gjør så mange kall mot getRighs. 
- [ ] Oppdater dokumentasjon

# SOAP-grensesnitt

## Sluttbrukersystem - SOAPbruk

Les analyse på [Sharepoint](https://digdir.sharepoint.com/:w:/r/sites/Autorisasjonogformidling/Delte%20dokumenter/General/Transformasjon%202.0%20-%203.0/Veien%20videre%20for%20autorisasjonsAPI%20i%20A2/SOAPtjenester%20for%20Sluttbrukersystemer.docx?d=w82c54ca27930418fbacbe7310bd37f50&csf=1&web=1&e=1SxMNw) (krever pålogging) 
Flølgende tjenester er vårt ansvar: 
![Image](https://github.com/Altinn/altinn-authorization/assets/25847572/27aaf2f7-c109-4345-aa52-418f8b229104)

## Tjenesteeier - SOAPbruk

Les analyse på [Sharepoint](https://digdir.sharepoint.com/:w:/r/sites/Autorisasjonogformidling/Delte%20dokumenter/General/Transformasjon%202.0%20-%203.0/Veien%20videre%20for%20autorisasjonsAPI%20i%20A2/SOAPtjenester%20for%20Tjenesteeiere.docx?d=w6bf95d523ae140a097bb5f53d223d1f2&csf=1&web=1&e=Ph7uwl) (krever pålogging)
Følgende tjenester er vårt ansvar: 

![Image](https://github.com/Altinn/altinn-authorization/assets/25847572/e6c7479c-1161-4c01-8023-f9227ae91095)

- [x] Lag issue for å fjerne denne tjenesten fra SOAP-dokumentasjon: https://altinn.github.io/docs/api/tjenesteeiere/soap/grensesnitt/autorisasjon/#importauthorizationpolicy

**Comment by rtafj** [comment]
Håndtert av Jon Kjetil i API-design oppgave.
