### ISSUE TITLE
Enable versioning of storage accounts containing XACML 

### ISSUE THREAD

**Issue by elsand** [Altinn/altinn-authorization#152]
## Description
Delegation policies will be saved in the same storage account as the apps' XACML policy (one blob per app/coveredby/offeredby-triplet). In order to preserve full history of delegation changes, we need to enable [versioning](https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview) . This, along the metadata we store i Postgre, will allow us to see the full state of a delegation policy at any given time.

## Considerations
Versioning is enabled on storage account-level, so any blob stored in this account will be subject to versioning. This may or may not be desirable depending on the type of blob being stored, but this can be somewhat controlled with [lifecycle management policies](https://docs.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview).

Versioning is not recommended used in conjunction with storage account snapshots, so if this is being used this need to be considered.

### Ops requirements
Cost and performance implications should be assessed, and lifecycle policies should be considered employed in order to optimize for both, with regards to:
* Hot vs cold access tiers
* How long versions should be preserved

## Acceptance criteria
* Blobs containing delegated policies must preserve all versions indefinitely
* Current version must always be in hot access tier for optimized performance 

## Specification tasks
- [ ] Determine if own storage account is required for delegation policies
- [ ] If not, assess performance implications for other storage needs
- [ ] If not, Assess cost implications for other storage needs
- [ ] If deemed necessary, design lifecycle policies 

## Development tasks
- [ ] Enable blob versioning via Terraform (either on existing accounts, or on new ones)

## Test
- [ ] For each storage account, under "Overview" section "Blob service", observe that "Versioning" is set to "Enabled".

## Definition of done
Verify that this issue meets [DoD](https://digdir-digitalisering.atlassian.net/wiki/spaces/T3KP/pages/5049246/Definition+of+Done) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by TheTechArch** [comment]
Implemented and in production
