### ISSUE TITLE
Define frontend architecture new authorization component

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#17]
## Description

When we now start the process of moving functionality from the Altinn 2 based architecture to the new Altinn 3 based architecture we need to finalize the architecture for frontend

## Consideration

The frontend architecture will be based around React but we need to consider several aspects

### SPA on separate URL or embedded in Razor

To be able to run the new React frontend there are two approaches

- Single SPA available on separate URL
- Embedded react app in current URL?

How will the decision affect how fast we can implement first level?
How will the decision affect how 

### Redux or not redux?
Should we continue to use redux? Assumption yes.,

### Saga or not Saga
Should we continue using sagas?

### Styling  

Should we use CSS, inline styling, or a combination? 

Or in typescript
https://vanilla-extract.style/

### Design
How should this component  be designed

Should it include a header/footer with all the needed functionality or should it just be the given panel created

### Reusable components

The components created need to be resued by other components. To promote reuse all components created should be created in the new StoryBook design system set ut by the Altinn team.  Components will be exported as NPM packages and used from the new authorizationadmin frontend

**Comment by Albertlarsen** [comment]
**Redux or not redux**

**Pros:**
1. Big community
    1. It has the biggest community of all the state management react tools. Makes it easy to solve problems when looking on stackoverflow etc.
2. Attractive to work with
    1. Makes it easy to transfer state between components
    2. Predictable states- it has something called “reduce” to handle this.
3. Easy maintenance
    1. It is strict on how code should be organized
4. Makes debugging and testing code easy
    1. Code can easily be evaluated as functions to alter the state of pure functions
    2. Makes Debugging easy through logging behaviour and status
5. Server rendering
    1. This is especially useful for the initial rendering to improve the user experience or optimize a search engine. Simply pass to the client-side the store created on the server.
6. Non-coders can track everything from actions to state shifts.
7. Chrome Extensions
    1. There exists a variety of extensions that can help with Redux, like devtools for debugging state changes
8. Reusability
    1. Functions that are isolated and perform a task can rely less on other modules in an app and a further advantage to functional programming via Redux is this decreased coupling.
9. Pure functions
    1. You don’t change current objects, instead, you return a new object. These functions do not depend on the state from which they are called, and for a given argument, they return only one result. They are very predictable for this reason. 
10. Good official documentation
    1. On https://redux.js.org/tutorials


Source: https://fintelics.medium.com/technical-benefits-of-using-redux-f7d345e7cc9c

**Cons:**
1. Strict
    1. This is also a con as it can make it harder for new people to learn the Redux-concepts.
    2. Restricted design.
2. Heavy
    1. As state is immutable in redux, the reducer updates the state by returning a new state every time which can cause excessive use of memory.
3. Security
    1. No encapsulation. Any component can access the data which can cause security issues.


Source: https://fintelics.medium.com/technical-benefits-of-using-redux-f7d345e7cc9c

**Comment by TheTechArch** [comment]
Closes this. Going for react  
https://docs.altinn.studio/technology/architecture/components/application/construction/altinn-platform/authorization/accessmanagment/
