### ISSUE TITLE
Update localtest PDP to support resource registry PRP

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#199]
### Description

When testing Access Manamgent we will need localtest to be able to authorize based on a XACML policy for the resource

### Tasks

-  [ ] Add XACML testdata for API scope delegation 
-  [ ] Update PRP in localtest to find policy based on resource id

**Comment by sivaglen** [comment]
Vi antar dette er gjort - det fungerer greit for Frontend nå så vi trenger ikke gjøre noe med dette nå.
