### ISSUE TITLE
Avgiverliste - gruppering av visning av slettede enheter

### ISSUE THREAD

**Issue by benedicteos** [Altinn/altinn-authorization#207]
Gruppering av visning av slettede enheter i oversikt over aktører/avgiverliste

**Comment by sivaglen** [comment]
@benedicteos - det er bestemt i dagens grooming at vi ikke flytter avgiverlisten fra A2 til A3 i forbindelse med migrering av lenketjenester. Jeg har tatt med denne som innspill til Issue for å flytte avgiverliste (som da skjer senere) og lukker denne. 
se [Gruppering av visning av slettede enheter i oversikt over aktører/avgiverliste](https://github.com/Altinn/altinn-access-management-frontend/issues/173)
