### ISSUE TITLE
Utvikle tester for Oversikt over delegerte API-ressurser, inkl slette eksisternde delegering

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-authorization#214]
Se https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163&t=t4xMCsuQH7p91n60-0 for skisser på flyten

Gitt at innlogget bruker har rollen Programmeringsgrensesnitt - API for en virksomhet
Og virksomheten har delegert tilgang til API-scopes til annen aktør
Når bruker velger panelet Tilgang til Programmeringsgrensesnitt - API
Da skal panelet ekspanderes
Og knapp for DelegerteAPI-tilganger skal vises og være klikkbar
Og knapp for Mottatt API-tilganger skal vises og være klikkbar
Og det skal være en blå informasjonsboks om hva API er

Når bruker klikker på knapp Delegerte API-tilganger
Da åpnes en Page med overskrift «Delegerte tilganger til Programmeringsgrensesnitt – API
Og det er en oversikt over aktører som har fått API- delegeringer fra virksomheten
Og antall API hver enkelt aktør har
Og det er en knapp for å delegere nytt API
Og det er en knapp for å redigere tilganger
Og det er en blå informasjonsboks om hva API er (samme som på ekspandert panel)

Når bruker klikker på en aktør som har fått delegert API tidligere
Da skal feltet ekspanderes
Og det skal være en liste over API-delegeringer som aktøren har fått tidligere
Og organisasjonsnummeret til aktøren skal vises rett under navnet

Når bruker klikker Rediger tilganger
Da skal knapp for Slett alle vises for hver av aktørene
Og Lagre-knapp skal være synlig men disablet
Og knapp for Avbryt skal være synlig og enablet

Når bruker klikker på en aktør i listen
Da skal feltet ekspanderes 
Og en liste over API som er delegert til aktøren skal vises
Og hvis man trykker rediger tilganger
Da skal hvert av API’ene skal ha en knapp for å slette delegeringen av det enkelte API’et
Og Lagre-knapp skal være synlig men disablet

Når bruker klikker på Slett-knapp for et API
Da skal teksten på Slett-knapp endres til Angre
Og navnet på API’et skal være overstreket
Og Lagre-knappen skal være enablet

Når bruker klikker Lagre 
Da skal bruker sendes tilbake til side med kollapset liste over aktører
Og teller for antall API tilganger for aktøren man har slettet på skal være redusert (hvis det ikke eksisterer flere delegeringer på aktøren, skal aktøren ikke vises i listen)

Når bruker klikker Angre-knapp
Da skal teksten på knappen endres til Slett
Og navnet på API’et skal ikke være overstreket
Og Lagre-knapp skal være synlig men disablet

**Comment by Albertlarsen** [comment]
@sivaglen @rtafj Gjort noen små justeringer. Ellers ser det bra ut 👍

**Comment by sivaglen** [comment]
@rtafj - kan vi få inn konkrete brukere (fra riktig testdatasett) og tjenester som skal benyttes i testene i denne beskrivelsen?

**Comment by acn-Sneha** [comment]
Tasken er merget i master, da lukker tasken @rtafj
