### ISSUE TITLE
Utvikle tester for delegering av Programmeringsgrensesnitt - API

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-authorization#220]
#66 
https://www.figma.com/file/ESobgAq072y7eQa4gP1JCKER/Profil?node-id=1209%3A8163&t=kNHF6YiOZgoRgt6y-0
**Delegere nytt API**

Gitt at innlogget bruker har rollen Programmeringsgrensesnitt - API for en virksomhet
Når bruker velger panelet Tilgang til Programmeringsgrensesnitt - API
Og bruker velger Gå til delegerte API tilganger
Og klikker Deleger nytt API
Da skal Pagen Gi tilgang til nytt API åpnes
Og en liste over allerede tildelte organisasjoner skal vises i venstre kolonne
Og høyre kolonne skal ha en tom liste for valgte organisasjoner
Og dersom man ikke har tildelt noen organisasjoner noen API-er skal man kunne skrive inn organisasjonsnummer på en bedrift man ønsker å gi tilgang til i input-feltet
Og søket gjøres når man har skrevet inn 9ende tall i inputfeltet
Og man kan ikke skrive inn bokstaver i inputfeltet
Og når man har valgt en organisasjon med plussknappen skal den legges i høyre kolonne
Og den disablede neste-knappen skal være enabled og man skal trykke på knappen
Og man går til neste side og en liste over tilgjengelige API skal vises i venstre kolonne
Og høyre kolonne skal ha en tom liste for valgte API
Og det skal være knapp for å filtrere på API tilbyder
Og det skal være et søkefelt for navn på API eller API-tilbyder
Og knapp for å gå tilbake (Forrige) skal være synlig og enablet
Og knapp for Neste skal være synlig og disabled frem til api er valgt.
Og når API er valgt da blir den enablet
Og når man trykker neste
Da skal oppsummeringsside vises
Og siden skal inneholde liste over API’er som er valgt
(Og hvis det er flere enn ett API, skal det være Slett-knapp ved hvert API – men siste kan ikke slettes)
Og siden skal inneholde liste over valgte mottakere
(Og hvis det er flere enn en mottaker API, skal det være Slett-knapp ved hver mottaker – men siste kan ikke slettes)
Og det skal være informasjon om at tilgangen gjelder til den blir trukket tilbake
Og Forrige-knapp skal være synlig og enablet
Og knapp for å bekrefte delegering skal være synlig og enablet
Når bruker klikker Bekreft delegering
Da skal kvitteringsside med samme info som oppsummeringssiden vises
Og knapp for Til totaloversikt skal være synlig og enablet

Når bruker klikker på pil-ned-knappen i Multiselect-boksen
Da skal en liste over API-tilbydere vises
Og et søkefelt for å søke etter tilbyder vises

Når bruker skriver i søkefeltet for tilbyder
Da skal det søkes i hele navnet (f.eks hvis man skriver ‘dig’ skal alt som ikke inneholder dig vises)
Og listen over tilbydere oppdateres legger treffene med best treff øverst
Og knapp for å filtrere skal være synlig og disablet

Når bruker markerer en eller flere tilbydere i filter-listen
Da skal checkbox ved tilbyders navn være avkrysset
Og bakgrunnene i raden skal være blå og det skal være et klikkbart kryss

Når bruker klikker på pil ned knapp for å vise filtrert utvalg
Da skal listen med accordionene for tilgjengelige API fra valgte tilbydere vises
Og API fra øvrige tilbyder skal ikke vises i listen
Og det skal være et +-tegn for å legge API’et i listen over API som skal delegeres

_//Ekspandere info om et API_
Når bruker klikker på ekspanderingspilen på et tilgjengelig API
Da skal raden ekspanderes
Og informasjon om API’et skal vises
Og det skal være et +-tegn for å legge API’et i listen over API som skal delegeres

_//Legge til et eller flere API i listen som skal delegeres_
Når bruker klikker på +-tegn for å legge til et API
Da skal valgt API vises i listen i høyre kolonne
Og det skal være et rødt minustegn for å angre/fjerne API fra listen i høyre kolonne
Og det skal være en ekspansjonspil for å vise mer info om API’et
Og det skal være mulig å legge til flere API fra listen i venstre kolonne
Og knapp for Neste skal være synlig og enablet
Og knapp for Forrige skal være synlig og enablet

 _// Finne/velge mottaker_
Når bruker klikker Neste (etter å ha lagt til API i delegeringslisten i høyre kolonne)
Da skal ny side vises med en oppsummeringsliste over valgte API
Og det skal vises hvem som er tilbyder av API
Og det skal være en Slett-knapp (lenke?) ved hver API og organisasjon i listen dersom hver liste har mer enn 1 element
Og det skal være en tom liste i høyre kolonne for virksomheter som skal få rettighet
Og Forrige-knapp skal være synlig og enablet
Og fullfør delegering skal være synlig og enablet

 _//Søke etter mottaker og få treff på virksomhet som har API-tilganger fra før_
Når bruker begynner å skrive inn et organisasjonsnummer i søkefeltet
Da skal listen over virksomheter som allerede har fått API-tilganger kun vise virksomheter som har orgnr som matcher søket

 _//Søke etter ny mottaker som ikke har API-tilganger fra før_
Når bruker skriver inn et orgnr på 9 siffer som ikke tilhører virksomheter som har API-tilganger fra før
Da skal det gjøres et søk mot [www.brreg.no](http://www.brreg.no/)
Og søkeresultatet skal vises under søkefeltet med virksomhetens navn og organisasjonsnummer
Og Avbryt-knapp skal være synlig og enablet 
Og Bekreft valg-knapp skal være synlig og enablet

 _//Legge til en mottaker som har tilgang til andre API fra før_
Når bruker klikker på +-tegnet for en virksomhet i listen

 _//Legge til organisasjon som ikke har API-tilganger fra før_
Når bruker klikker pluss-knapp
_//Felles flyt for både ny og eksisterende virksomheter_
Da skal valgt virksomhet vises i listen i høyre kolonne
Og det skal være et rødt kryss for å angre/fjerne virksomheten 
Og Forrige-knapp skal være synlig og enablet
Og Neste-knapp skal være synlig og enablet

_//Hvis man skal angre et API som er lagt i høyre kolonne_ 
Når bruker klikker på rødt kryss ved et API som er lagt til i høyre kolonne
Da skal API’et fjernes fra listen i høyre kolonne
Og vises i listen over tilgjengelige API i venstre kolonne

_//Hvis man skal angre en mottaker som er lagt til i høyre kolonne_
Når bruker klikker på rødt kryss ved en aktør
Da skal aktøren fjernes fra listen i høyre kolonne
Og vises i listen over aktører i venstre kolonne

_//Forrige-knapp_
Når bruker klikker på Forrige-knapp
Da skal bruker tas tilbake til det foregående steget

**Comment by rtafj** [comment]
#66

**Comment by Albertlarsen** [comment]
@rtafj @sivaglen Akkurat gått gjennom og gjort noen justeringer. Det ser bra ut :)

**Comment by sivaglen** [comment]
@rtafj - kan vi få inn konkrete brukere (fra riktig testdatasett) og tjenester som skal benyttes i testene i denne beskrivelsen?

**Comment by anishastphen** [comment]
tasken er completed, lukker tasken
men det gjenstår riktig sett opp av data - MinID brukere
@rtafj
