### ISSUE TITLE
Oppdater inforside for tilgangsstyrer Delegerbare API ressurser

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#225]
Denne siden må oppdateres med nye printscreen og beskrivelser fra nytt GUI for å administrere delegerbare API ressurser: 
https://altinn.github.io/docs/utviklingsguider/api-delegering/tilgangsstyrer/

**Comment by jonkjetiloye** [comment]
Ser det også er en egen side på studio docs:
https://docs.altinn.studio/api/authentication/delegate-scopes/

**Comment by rtafj** [comment]
Legges i blocked i påvente av deploy av funksjonalitet

**Comment by sivaglen** [comment]
@lovoll - er det riktig forstått at du er ferdig med å oppdatere dokumentasjon  i https://github.com/Altinn/altinn-studio-docs/pull/893/commits og https://github.com/Altinn/docs/pull/513? 
Og at dette bare venter på at vi skal bli ferdig med flytting i prod?
