### ISSUE TITLE
Is it possible to use the real authorization microservice with Localtest?

### ISSUE THREAD

**Issue by ivarne** [Altinn/altinn-authorization#233]
### Question

I'm having an issue where the authorization rules of an app behaves differently in tt02/prod and in localtest. Luckily the behaviour is problematic only in Localtest, but I'm having a hard time trying to figure out what the expected behaviour should be.

It seems like it could be possible to use the real authorization service to test for differences. Is that documented anywhere?

**Comment by sivaglen** [comment]
Det er mulig å kjøre autorisasjon lokalt - men det er veldig mye som må settes opp (storage, plattform osv) og vi mener ikke du som ekstern utvikler kan gjøre det. 

@RonnyB71 - har du noe å tilføre?
