### ISSUE TITLE
Go to delegated API accesses -> bluescreen

### ISSUE THREAD

**Issue by ToreMasoy** [Altinn/altinn-authorization#287]
1. Log in with any DAGL in AT23
2. Represent a organization
3. Profile
4. Access to the Application Programming Interface (API)
5. Go to delegated API accesses
6. A blue screen is presented

Error code: GET 404 https://am.ui.at23.altinn.cloud/accessmanagement/localizations/en-US.json

Refreshing the page works. It occurs only first time after logging in.

**Comment by annerisbakk** [comment]
@acn-dgopa Kan du ta en vurdering av denne?

**Comment by Albertlarsen** [comment]
@ToreMasoy @annerisbakk @sivaglen  har deployet en midlertidig fix på denne som fjerner blue screenen, løsningen går ut på å defaulte til norsk.


@TheTechArch Vi bør nok sikkert lage en mer permanent løsning fix ved å sette cookie index-filen i BFF i morgen.

**Comment by Albertlarsen** [comment]
Issue for permanent fix: https://github.com/Altinn/altinn-access-management-frontend/issues/239
