### ISSUE TITLE
Integrate PDP with Altinn Resource Registry

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#32]
### Description

We need to update logic in PDP so policies can be retrieved from Resource Registry.

Resource registry will provide an endpoint both for policies for Apps created in Altinn Studio and policies created for Resources in Altinn Resource Registry 

### Additional Information

This needs to be added as configurable in the first iteration. First when Altinn Policies is production ready, we will permanently call Altinn Policies to get it. 

### Tasks

- [ ] Add a separate PRP service that retrieves policy from Altinn Policy instead from local service. 

### Acceptance Criteria

- [ ] Supports

**Comment by jonkjetiloye** [comment]
Delivered in PR:
https://github.com/Altinn/altinn-authorization/pull/137
