### ISSUE TITLE
Alfabetisering av underenheter

### ISSUE THREAD

**Issue by annerisbakk** [Altinn/altinn-authorization#326]
Endringsønske fra NFK - Nordland fylkeskommune [https://github.com/Altinn/altinn-support-private/issues/1126]
Ønsker mulighet til å alfabetisere underenheter på "hoved"-organisasjonsnumre som vi har i Nordlan fylkeskommune. Dette vil lette arbeidet, spesielt for arkivarer betraktelig. Se skjermdump på opprinnelig supportsak.

**Comment by annerisbakk** [comment]
Usikker på om det er riktig repository

**Comment by sivaglen** [comment]
Lagt inn som kommentar om ønsket på Nøtt https://github.com/Altinn/altinn-access-management/issues/82

**Comment by annerisbakk** [comment]
@sivaglen Da lukker jeg saken her :)
