### ISSUE TITLE
Plan for å flytte delegerbare API ressurser i PROD miljø

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#331]
## Status for flytting

2. mai  ble tjenestene flyttet i TT miljøet. 
Tidspunkt for flytting av tjenester i Prodmljøet 

I en overgangsfase vil det etter 2. mai ikke være mulig for tjenesteeiere å bruke API for å opprette nye Delegationschemes. Dette må da gjøres ved å sende henvendelse til servicedesk@altinn.no og Altinn vil opprette nye tjenester på vegne av tjenesteeier. 
Nye API for å opprette Delegationschemes vil bli tilgjengelig høsten 2023. 

## 
```[tasklist]
### Nødvendig forberedelse før flytting i prod:
- [ ] https://github.com/Altinn/altinn-authorization/issues/341
- [x] Vi må lage teortisk en plan for hva som må gjøres hvis vi ser at vi må rulle tilbake etter at løsningen har vært en stund i drift i Altinn 3 - Jon Kjetil
- [x] Sørge for at våre folk får testet API skikkelig i prod - dette må vi teste på forhånd. Har Ivar sertifikat? - Ragnhild
- [x] Ytelsesteste - Henning har eksisterende tester som kan modifiseres litt før de kan benyttes.
- [x] Gå gjennom verifikajsonstester og sørg for at man tester alle scenario - Anisha, med flere
- [x] Sjekk med Espen om prodsettingskalender i prod - finn passelig dato (når det ikke skjer så mye annet) - Raghnild
- [x] Kall inn til felles møte for alle som skal delta i produksjonssetting - Ragnhild
- [x] Sjekk med Norsk Helsenett at API fungerer for de i TT miljø - Siv
- [ ] https://github.com/Altinn/altinn-access-management-frontend/issues/212
```

### Description

Det er ønskelig å flytte alle Delegerbare API-ressurser fra Altinn og deretter "slå av" API og mulighet for å opprette nye i 2.0. 
Fra da skal kun API og delegeringer registrert i 3.0 brukes av makskinporten og tjenesteeieren

### Forutsetning før migrering
- All kode er depoloyet til A3 og A2 plattformen
- Nye roller og systemressurser er på plass (A2) 
- Alle delegationschemes er oppdatert med de nye tekstene som er meldt tilbake. 
- Undersøkt om det er mye "tulle-delegationschemes" som er lagt i TT2. Evt rydde opp i data hvis dette er tilfellet. 

#### Trinn 0

1. Innfør frysperiode på  Delegationschemes. Varsler tjenesteeiere
Ansvar: Siv

2. Forberede delegering i A2 for delegationscheme for sjekk etter migrering
Ansvar: Anisha

#### Trinn 1

1. Tech-team tar ut halvparten av appservere av last
1.1 Slår på featuretoggle: MaskinportenDelegationsDisableAltinnII
1.2 Clearer cache (iisreset)
1.3 Varmer opp serverne
1.4 Setter disse inn i last igjen
Ansvar: Simon

2. Tech-team tar resten av app servere ut av last og forbereder disse for Trinn 2 Steg 2.
2.1 Slår på featuretoggle: MaskinportenDelegationsDisableAltinnII
2.2 Slår på featuretoggle: MaskinportenDelegationsInAltinnPlatform
2.3 Clearer cache (iisreset)
2.4 Varmer opp serverne
**NB!: Disse settes ikke inn før Trinn 2 Steg 2**
Ansvar: Simon

3. Verifisere i enkeltdelegering i A2 at delegation schemes ikke lenger er tilgjengelig

**Fra nå kan ingen delegere eller lage nye delegationschemes.  Dette vil ikke være tilgjengelig før etter at hele trinn 2 er ferdig.**

4. Kjøre batchjobb som flytter alle DelegationScheme til Ressursregister i A3 og oppretter policyer for disse. 
Ansvar: Remi

5. Verifiser at alle ressurser er registert
Ansvar: Alle 

6. Test at det er mulig å delegere nye rettigheter til ressurs i Altinn3 (via "hemmelig lenke") 
Ansvar: Anisha

7. Kall API som proxy kaller i A3 og se at man får forventet svar (at ny delegering dukker opp) - (https://platform.altinn.no/accessmanagement/api/v1/maskinporten/delegations?scope={})
Ansvar: Anisha

8. Kjøre batchjobb som flytter alle delegeringspolicyer fra A2 til A3
Ansvar: Remi

9.  Verifiser at delegeringer er registert
Ansvar:
GUI / API - Anisha (https://platform.altinn.no/accessmanagement/api/v1/maskinporten/delegations?scope={})
DB - Jon Kjetil

#### Trinn 2

1. Verifiser Maskinporten proxy API fungerer fra A2 i testløp (?) (https://www.altinn.no/maskinporten-api/delegations/)
Ansvar: Anisha (?)

2. Last switch: Serverene i testløp (preppet i Trinn 1 Steg 2) settes i last
Ansvar: Simon

**Fra nå går A2 Maskinporten API kall til A3**

3. Verifisert at Proxy Maskinporten API fungerer
Ansvar:
Maskinporten: Randi / vakt
Verifiser API manuelt:  Anisha ( (https://www.altinn.no/maskinporten-api/delegations/))
Monitorerer logger: Jon Kjetil

4. Toggle switch:  Ny profil A2 -> A3
4.1 Servere i last: slå på featuretoggle: ApiAdministration
4.2 Servere utenfor last: Slå på featuretoggle: MaskinportenDelegationsInAltinnPlatform
4.3 Servere utenfor last: Slå på featuretoggle: ApiAdministration
Ansvar: Remi / Simon

5. Verifiser at nytt panel er tilgjengelig fra Profil
Ansvar: Anisha / Alle

**Fra nå kan nytt GUI for API delegering benyttes**

6. Alle servere settes i last gitt at vi er fornøyde med resultatet

#### Trinn 3
Opphev frysperiode på DelegationSchemes. Send varsling til tjenesteeiere
Ansvar: Siv 

####  Trinn 4 - Opprydding

1. slett delegeringer i A2 -> rydder opp i avgiverlista
- [ ] Lag en jobb for å sette delegationschemes til uløpt og en som setter de tilbake til det de er før. - Remi
- [x] Lag issue på å slette delegeringer (US 63551)

**Comment by jonkjetiloye** [comment]
@sivaglen:
La også til infrastruktur issuen som gjenstår i lista over nødvendige forberedelser før prod.
Hvor det gjenstår fortsatt hvertfall to ting:

1. Herding av KeyVaults
2. Infrastruktur for Prod (som infrastruktur sikkerhetsmessig er avhengig pkt. 1.)

### Teoretisk plan for i tilfelle tilbakerulling:

1. Script kjøres for å aktivere DelegationSchemes i Altinn 2 (dersom script for å deaktivere de er kjørt i utgangspunktet)
2. Revert feature toggles:
2.1 Dersom vi fortsatt har app-servere utenfor last med feature toggle av kan disse switches inn i last direkte
2.2 Dersom alle app-servere er i last med feature på, må vi gjennomføre revers av Trinn 1 Steg 1
3. Alle nye delegeringer eller slettinger i Altinn 3 vil gå tapt. 
3.1 Vi kan her gjøre uttrekk av nye endringer gjort i Altinn 3 og hvem som har utført disse for at disse kan kontaktes og varsles om at de evt. må gjøre dette på nytt i Altinn 2.

**Comment by anishastphen** [comment]
@sivaglen @rtafj @jonkjetiloye ift verifikasjonstest i prod
1.	Må testes med sikkerhetsnivå 3 eller 4 brukere, da må vi bruke reele brukere for testing (siden test brukere har kun nivå 2 sikkerhetsnivå)
2.	Delering av delegation schemes bør gjøres i forkant i A2 for verifikasjon -  de som har BEST,BOBE,DAGL,DTPR,DTSO,INNH,KEMN,KOMP,LEDE,REPR kan delegere delegation schemes. Kanskje Remi kan hjelpe å fikse det slik at jeg blir DAGL for en test org?
3.	Må finne en test delegation scheme (A2) som kan brukes for testing i punkt 2
4.	Har vi mulighet til å opprette MakinPortenSchema i PROD som kan brukes for test?
5.	Hvordan tester vi API proxy - /maskinporten-api/delegations/?scope={}, har vi mulighet til å generere et token?

**Comment by sivaglen** [comment]
@anishastphen 
Er følgende behov for testobjekter i prod riktig forstått? 

1. En tjeneste av typen delegationscheme i A2 hvor en konsumentorg har delegert rettighet til en systemleverandørorg før vi starter flytting av tjeneste
2. Konsumentorg som har en DAGL som kan logge på med nivå 3 og 4
3. Systemleverandørorg som har DAGL som kan logge på med nivå 3 og 4

**Comment by anishastphen** [comment]
@sivaglen jeg må finne en delegation scheme som kan brukes for test her.
Angående DAGL brukere - det skal fikse ved hjelp av Remi i dag. Planen er å bruke test org og reele personer med nivå3/niva4 blir DAGL for disse test org.

**Comment by rtafj** [comment]
Lukker denne saken - opprydding følges opp i egne issues (388 og 389)
