### ISSUE TITLE
Lage K6 test for feil som ble oppdaget - Ivar

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-authorization#341]
K6 testene for maskinporten i Access Management feiler etter RightsDelegationResults ble oppdatert. 
Disse to sjekkene feiler:
`(r) => r.json('rightDelegationResults.0.action.id') === 'urn:oasis:names:tc:xacml:1.0:action:action-id'`
`(r) => r.json('rightDelegationResults.0.action.value') === 'ScopeAccess'`
Siden `action` har blitt byttet fra å være AttributeMatch til å være en string, må disse to linjene erstattes med:
`(r) => r.json('rightDelegationResults.0.action') === 'ScopeAccess'`

Det finnes to tester der action skal være `read` i stedet for `ScopeAccess`

**Comment by jonkjetiloye** [comment]
@ivartryti Denne var lite beskrivende. Enten bør den fylles ut for hva det gjelder (om du fortsatt husker :P) eller lukkes

**Comment by ivartryti** [comment]
@jonkjetiloye Jeg har glemt hvorfor jeg lagde denne, men vi har jo noen tester som feiler nå, så jeg beskrev det i stedet for :)

**Comment by ivartryti** [comment]
fikset i https://github.com/Altinn/altinn-access-management/pull/580
