### ISSUE TITLE
Update configuration: PostgreSQL servers have a new hostname (CNAME record)

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-authorization#369]
### Description

All PostgreSQL server now have a CNAME that applications should use to access the server. 

CNAME records have been added in case of disaster recovery and other activities where a new server would need to be established under a new hostname. The CNAME record works as a form of alias to make it possible to switch between servers behind the scene without the need to update the application configuration.

### Additional Information

The list of CNAME records: 
- https://pedia.altinn.cloud/altinn-3/ops/backup-recovery/platform/postgresql/#dns
- https://github.com/Altinn/altinn-platform/issues/457

**Comment by Thuen** [comment]
Duplicate - Resolved in : https://github.com/Altinn/altinn-authorization/issues/430
