### ISSUE TITLE
Opprydding etter flytting av delegerbare API-ressurser

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-authorization#389]
### Description

Lag en jobb for å sette delegationschemes til uløpt, og en som setter de tilbake til det de er før

jft trinn 4 i https://github.com/Altinn/altinn-authorization/issues/331

**Comment by jonkjetiloye** [comment]
Lukker denne. Script for dette hadde Remi laget som vi brukte ved utrulling av API delegering, som er gjennomført for lenge siden
