### ISSUE TITLE
Activate feature toggle for Storage API for Instance metadata

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#401]
### Description

Ref.: https://github.com/Altinn/altinn-authorization/pull/346

Instance metadata should now be fetched through the new storage API instead of a directly from Cosmos.

values.yaml for environment variables must be updated with new API endpoint (through local cluster not APIM), and activating the feature toggle config value: GeneralSettings__UseStorageApiForInstanceAuthInfo

### Additional Information

PR for updating values.yaml:
https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/689?_a=files

**Comment by jonkjetiloye** [comment]
@rtafj @sivaglen @annerisbakk 
Jeg forstår det som på @HenningNormann at core-teamet ønsker at vi tester utrullingen av å ta i bruk det nye storage APIet fra authorization. Da må det kanskje vurderes i forhold til backloggen og hvem/hva/når/hvor.

**Comment by rtafj** [comment]
@anishastphen  skal se på hvordan dette kan testes når hun er ferdig med pipeline for Cypress-tester.

@jonkjetiloye  @annerisbakk @sivaglen

**Comment by anishastphen** [comment]
testet OK
