### ISSUE TITLE
Update postgres connectionstring with CNAME

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#430]
### Description

Det er innført bruk av CNAME  for å koble seg til PostgreSQL. (man kan koble seg mot databasen både med servernavn og CNAME). Grunnen til at det er innførert CNAME er at når det tas en restore av PostgreSQL vil det opprettes en ny PostgreSQL server med nytt navn og da er det enklere å gjøre endringen i DNS enn oppdatere appene.

Her er et eksempel for connection string som benytter CNAME
- name: PostgreSQLSettings__ConnectionString
      value: Host=at22-authorization-postgre.altinn.cloud.altinn.cloud;Port=5432;Username=platform_authorization;Password={0};Database=authorizationdb;SslMode=Require;Trust Server Certificate=true;

CNAME er satt opp i alle miljøer.
for tt02 og prod er domenet altinn.no, mens i de andre benyttes altinn.cloud

### Tasks

Oppdatere alle values.yaml filer for alle repo/applikasjoner som har direkte kobling til Authorization postgres databasen

- [x] Authorization
- [x] Access Management
- [x] Resource Registry

**Comment by Thuen** [comment]
Alle connectionstrings er nå oppdatert for authorizationdb. Måtte i tillegg legge til SslMode=Require;Trust Server Certificate=true; for at connections skulle fungere.

**Comment by Thuen** [comment]
Alle connectionstrings er nå oppdatert for authorizationdb. Måtte i tillegg legge til SslMode=Require;Trust Server Certificate=true; for at connections skulle fungere.
