### ISSUE TITLE
Possible to add duplicate rules with different casing of action-id

### ISSUE THREAD

**Issue by jeevananthank** [Altinn/altinn-authorization#55]
## Description
It is possible to add duplicate rules with platform/authorization `AllRules` API with different casing on the action-id.
ex., write, Write - both are recognized as separate rules

## To Reproduce
1. Send a POST call to platform/authorization to add a rule giving write access on an app with action-id: `write`
`/authorization/api/v1/delegations/AddRules`
2. Send the same request with action-id: `Write`
3. Two difference rules are created and saved in the storage.

## Expected behavior
there should be a validation on the casing of the `action-id`, the rules can be created only with the casing of the action-id in policy.xml of the app.

## Additional info
env: at21

**Comment by sivaglen** [comment]
@TheTechArch #7121 er lukket. Kan vi lukke denne også?

**Comment by jonkjetiloye** [comment]
@sivaglen Denne buggen gjelder de "interne" delegerings-API (som f.eks SBL bruker nå man delegerer en app i A2) som ikke har noe validering.

@sivaglen 
Så lenge dette bare er internt og at vi i eksterne delegerings-API faktisk gjør autorisasjon/validering av at autentisert bruker kan delegere rettighetene vil dette være styrt av om tjenesteeier selv i egen app/ressurs policy har spesifisert MatchId for action til case-sensitiv (urn:oasis:names:tc:xacml:1.0:function:string-equal) eller ikke (urn:oasis:names:tc:xacml:3.0:function:string-equal-ignore-case)
F.eks
```
<xacml:Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
    <xacml:AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</xacml:AttributeValue>
    <xacml:AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false"/>
</xacml:Match>
```

Så ja, tenker dette er noe vi ikke gjør noe med i intern API, men er noe vil bli validert/autorisert i access-management API
