### ISSUE TITLE
Update Authorization component to support app delegations

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#6]
## Description

Currently, the Altinn 3 platform only supports delegation through roles.  We need to support that we include delegated XACML Policies when evaluating a request. 

## Considerations

The delegated policy will be stored in the same Azure Blob storage used for XACML policies. 

There will be a Cosmos collection that can be used to identify 

### Authorization sequence

The below sequence show how the upgraded PDP should work

![image](https://user-images.githubusercontent.com/13309071/92011048-cf546980-ed4a-11ea-9442-15f05280611e.png)

- API receives a request 
- The authentication token is validated and identity created on the request context
- Policy enforcement point is trigged
- PEP calls PDP as an XACML JSON authorization request with the parameters
- PDP calls context handler to enrich request (reporter, app info, state ++)
- Context handler calls storage to get information about instance/app
- Context handler calls Altinn 2 to get roles user has for owner of instance
- Context handler adds subject of resource information to the authorization request
- PDP calls PRP to get the configurated XACML Policy for the given app
- PDP identifies the rules
- PDP authorizes based on relevant rules
- If not authorized calls PRP to see if there are any delegated roles
- PRP identifies if the user has any key roles that should be included when searching for delegation
- PRP identifies if the unit has any parents that should be included in the search (rights to parents is also implicit given on child)
- PRP searches the database for any delegation matching
- PDP goes through every delegated policy and checks if the user is authorized.

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
- [ ] Update decision point logic to look for delegated policies if user is not authorized (Not applicable)
- [ ] Update PRP to identify all key role parties user has 
- [ ] Update PRP to search for all policies for that given app that has been delegated to 

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by sivaglen** [comment]
@TheTechArch kan vi lukke denne issuen?

**Comment by TheTechArch** [comment]
Implemented and in production
