### ISSUE TITLE
Som Altinn skal jeg kunne registrere autorisasjonsregl til et delgationscheme som finnes i ResourceRegistry

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-authorization#61]
### Description

Delegerbar API-ressurs (delegationscheme) som registreres i US [#60 ] skal ha sin egen autorisasjonsregel som angir hva som må til for å delegere ressursen til et organisasjonsnummer. 
Det skal være mulig å registrere forskjellige autorisasjonsregler på de ulike delegationschemes. 
Regelen skal kunne innholde henvisning til 2.0 rolle, 3.0 tilgangsgruppe og ER rolle

For å delegere ressursen så kreves en av følgende 

-  HADMIN (2.0 rolle)
-  Delegerbare API ressurser (3.0 tilgangsgruppe, se [her](https://altinn.github.io/docs/utviklingsguider/styring-av-tilgang/for-tjenesteeier/forslag-tilgangsgrupper/#offentlige-digitale-tjenester-tverrfaglig)
- ER-roller
  - Bestyrende reder (BEST)
  - Bostyrer (BOBE)
  - Daglig leder / administrerende direktør (DAGL)
  - Deltaker med delt ansvar (DTPR)
  - Deltaker med fullt ansvar (DTSO)
  - Innehaver (INNH)
  - Komplementar (KOMP)
  - Kontaktperson i Adm. enhet - offentlig sektor (KEMN)
  - Styrets leder (LEDE)
  - Norsk representant for utenlandsk enhet (REPR)

Denne tilhører epic: https://github.com/Altinn/altinn-authorization/issues/59

**Comment by jonkjetiloye** [comment]
Main implementation of API and policy repository for ResourceRegistry added in commit:
https://github.com/Altinn/altinn-resource-registry/commit/da9577c1fbef7baff744194b23b5fe33cac46147

Some validation logic and unit tests implemented in commit:
https://github.com/Altinn/altinn-resource-registry/commit/21ac252ceb0b6546a7f6bc9023d737291991b48a

**Comment by sivaglen** [comment]
@jonkjetiloye og @rtafj det er vel greit å lukke denne?

**Comment by jonkjetiloye** [comment]
@sivaglen @rtafj Den ligger vel åpen og i test kolonnen med tanke på manglende automatiserte tester.
Ellers kan man vel argumentere for at denne ligger i feil repo og burde flyttes til ressursregisteret, gitt at det går ut på å registrere Xacml policy for en ressurs?

**Comment by rtafj** [comment]
@acn-Sneha @anishastphen - er denne dekket av automatiserte tester på delegerbare API?

**Comment by anishastphen** [comment]
nei, den er ikke dekket. @rtafj 
trenger litt bedre forståelse om hva bør sjekkes her? @jonkjetiloye 
cc: @acn-Sneha

**Comment by jonkjetiloye** [comment]
@rtafj @anishastphen @acn-Sneha
Dette er vel i så fall opprettelse av ressurs og policy for en MaskinportenSchema ressurs i Ressursregisteret.

Usikker på om det er noe som er ønsket å ha automatiserte tester på. Må i så fall være forsøk på å oppdatere en eksisterende ressurs og policy så man ikke oversvømmer registeret med test ressurser/data.

**Comment by acn-Sneha** [comment]
@rtafj @jonkjetiloye magler det dekkning av automation testing her? Trenger litt mer forståelse her.

**Comment by Nyeng** [comment]
@jonkjetiloye vi trenger mer kontekst for å vite om denne kan lukkes eller testes.
