### ISSUE TITLE
Configure ipaddress fowarding on app

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-authorization#662]
### Description

Right now, the ipaddress of the app cluster is being logged into the authorization logg. Auditlog requires that we log the client's ipaddress. This requires some changes in the app cluster configuration.

### Tasks

- [x] Configure træfikk to forward the client ip from app

### Acceptance Criteria

- [x] Client ipadress (from app) is accessible in the authorization platform component via ["X-Forwarded-For"]

**Comment by bengtfredh** [comment]
We made changes to loadbalancer and ingress to send client ip as "x-forwarded-for" and "x-real-ip"
This is deployed in ttd-at{21-24} and ttd-tt02 ready for testing.
