### ISSUE TITLE
External PDP Access

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-authorization#676]
### Description

As a org I should be able to call Altinn to verify if a user or organization is authorized to performed a given action on a resource registered in the resource registry

### Additional Information

This endpoint will also be used from Dialogporten.

### Acceptance Criteria

- API should be available for registered org that are permitted to access
- API should follow relevant standards as XACML
- It should be possible to use organization numbers and ssn for identification. There is no need for internal Altinn specific identities

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-authorization/issues/675
- [ ] https://github.com/Altinn/altinn-authorization/issues/448
```

**Comment by annerisbakk** [comment]
@TheTechArch Er denne i prod og kan lukkes?

**Comment by TheTechArch** [comment]
In production
