### ISSUE TITLE
Automatisert uthenting av transaksjoner fra Maskinporten mot autorisasjon

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-authorization#710]
Hver måned rapporterer vi autorisasjons-transaksjoner som er gjort fra maskinporten, og dett er en manuell jobb idag. Ønsker å automatisere denne jobben.

**Comment by jonkjetiloye** [comment]
Duplikat av https://github.com/Altinn/altinn-authorization/issues/776
lukker denne
