### ISSUE TITLE
The call to SBL Bridge to fetch roles for the user fails with a 500 Internal Server Error

### ISSUE THREAD

**Issue by nairaz** [Altinn/altinn-authorization#832]
### Description of the bug

The call to SBL Bridge to fetch roles for the user fails with a 500 Internal Server Error

From the logs, it's observed that the call to Altinn 3 to fetch recipients and delegations is failing, where the user receives a 403 Forbidden error. Even though they are logged in with level 3 access and are a DAILY user

The hypothesis is that users with  "fortrolig" and "strengt fortrolig" (codes 6 and 7 ) are failing

**logs:** 
[https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%2[…]-8ef6-d0b6ddcfd9a4%22%2C%22eventTable%22%3A%22requests%22%7D](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%22de41df22-8dd0-435b-98dd-6152cd371e92%22%2C%22ResourceGroup%22%3A%22altinnplatform-at22-rg%22%2C%22Name%22%3A%22at22-platform-ai%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252Fde41df22-8dd0-435b-98dd-6152cd371e92%252FresourceGroups%252Faltinnplatform-at22-rg%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fat22-platform-ai%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%22a8d913e7-faed-11ee-8f96-0022486fe6cd%22%2C%22timestamp%22%3A%222024-04-15T06%3A00%3A28.960Z%22%2C%22cacheId%22%3A%22848675df-02b4-4f99-8ef6-d0b6ddcfd9a4%22%2C%22eventTable%22%3A%22requests%22%7D)

### Steps To Reproduce

Users with confidential and strictly confidential (kode 6 og 7 "fortrolig" og "strengt fortrolig"  roles are failing.

1. Log in with user 05895495109 or 018652 99334 in https://info.at22.altinn.cloud/
2. Select the organization.
3. Choose " skjema og tjenester du har rettighet til" or "Andre med rettigheter til virksomheten"
4. Fails with the following error message
5. 
![image](https://github.com/Altinn/altinn-authorization/assets/160860495/16d64992-569d-4409-a0d5-c79e54573b64)

**Comment by jonkjetiloye** [comment]
The problem stems from a change made in Altinn 2 by Team Core ([Bug 64125](https://dev.azure.com/digdir/Altinn/_workitems/edit/64125/))
The issue has now been solved in Altinn 2 through the [Bug 64209](https://dev.azure.com/digdir/Altinn/_workitems/edit/64209/)
