### ISSUE TITLE
Remove negative K6 tests for DeleteRules which cause error alerts for deploy

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization#87]
### Description

There are at least two actions for DeleteRules which cause errors when DelegationEvent Function tries to sync the revokes to SBL Bridge. Example from AT23:
https://altinndevops.slack.com/archives/CMJ125ZBJ/p1665052100007819

Timestamp: 06.10.2022 12:24:14
AltinnException ErrorMessage: Failed to revoke authorization rule for the platform delegation event id: 101054

Timestamp: 06.10.2022 12:24:22
AltinnException ErrorMessage: Failed to revoke authorization rule for the platform delegation event id: 101057

Negative tests should be kept out of K6 tests and instead be added as integration tests in the repo if not already covered.

### Tasks

- [x] Remove/update K6 tests causing errors

### Acceptance Criterias

- [ ] K6 test execution should not cause alerts in [#alerts-test](https://altinndevops.slack.com/archives/CMJ125ZBJ) slack channel for a normal/successful test execution run.

**Comment by ivartryti** [comment]
PR: https://github.com/Altinn/altinn-studio/pull/9064

**Comment by ivartryti** [comment]
Removed two negative tests from the list of tests to run.
