### ISSUE TITLE
RFC: Swagger for defining API between 2.0 PAP and 3.0 PAP 

### ISSUE THREAD

**Issue by elsand** [Altinn/altinn-authorization#9]
## Description

This issue discusses the PAP API that should be implemented for supporting 3.0 app delegations.

A proposal is available at https://app.swaggerhub.com/apis/Altinn/Rights-3.0 

This API will affect several other issues:

Altinn/altinn-studio#4772 API for listing delegable actions
Altinn/altinn-studio#4773 API for delegating app to user/party (storing a delegation)	 
Altinn/altinn-studio#4777 API for listing delegated rights
Altinn/altinn-authorization#8 API for deleting a delegation

Which are all requirements for

Altinn/altinn-authorization#2 API for delegating Altinn 3 app in Altinn 2
Altinn/altinn-authorization#3 Update delegation controller (in 2.0)

and ultimately

Altinn/altinn-authorization#6 Update authorization component to support app delegations

## API overview

The API should be able to
- List delegable actions for given user on behalf a reportee (offeredby) for a specific app
- List active policies for a given coveredby on behalf of a offeredby for a specific app (including those granted indirectly through inheritance)
- Create new policies (directly delegated)
- Add new rules to existing policies (directly delegated)
- Delete policies
- Delete individual rules within policies

## Terms used
- *Action* = A operation (read, write, confirm etc) as defined in on or more rules in a given app's XACML-policy
- *Right* = A right that someone has been given (or has inherited) granting a single action for a app on behalf of a reportee (can be limited to a specific task/event-state, but this is abstracted for the user)
- *Policy* = A delegated policy describing an {app,offeredBy,coveredBy}-tuple listing all rules granting someone  (coveredby) rights on behalf of a reportee (offeredby) 
- *Rule* = A specific rule within a policy

## Solution 

The API will be policy-oriented, and allow for adding and deleting specific rules within policies. The solution is based on using existing storage accounts for the apps which already stores "static" policies, ie. role requirements. A Postgre database with a single table will contain a list of delegation events, all pointing to a specific version of the policy, and have a schema like

```
guid      PolicyId
string    AltinnAppID
int       OfferedByPartyId
int       CoveredByPartyId
int       CoveredByUserId
int       PerformingUserId
datetime  Created
string    BlobStoragePolicyPath
string    BlobStorageVersionId
```
The table should at least have the following indexes to support the currently known querying scenarios;
- `PolicyId` (for single policy lookups)
- `Created` (in order to get most current policy version)
- `AltinnAppID_OfferedByPartyId_CoveredByPartyId_CoveredByUserId` (compound index for listing existing delegations in PAP-context)

The filepaths will have a meaningful naming policy for maintainability reasons, ie. 
`delagatedpolicies/{offeredBy}/{coveredByPartyId}_{coveredByUserId}.xml` (either coveredByPartyId or coveredByUserId is set to `0` if the delegation is to a person or an organization, respectively. Both if enterprise user)

See the most current OAS-specification at https://app.swaggerhub.com/apis/Altinn/Rights-3.0/ for further details.

## Discussion (history)

**These are the points previously raised and resolved after analysis, discussion and various adjustments**

~~The proposed API exposes a list of delegations. This can span several actions begin delegated at different times by different administrators, either given directly or applying because of inheritance.~~ The proposed API is now policy-oriented, and does not expose history information - only current policies.

The 2.0 PAP will then have to utilize the list of delegable actions in conjuction with the list of already existing delegations, and handle:
- Potential duplicates (a given action being given through multiple delegated policies)
    - _Duplicates aren't technically an issue with the current RuleCombiningPolicy - the PDP will just grant access on first matching rule_
- Inheritance (in case the coveredby has keyroles, which also should be granted rights given to the parties he/she has key roles for - or - if offeredby is a subunit, so that rights given by its parent should also apply)
    - _The API will return separate policies depending on whether they are direct or inherited_
- Deletion (this works differently in 2.0 portal and REST API. In the portal all rules given directly on a service are deleted, while in REST it is possible to delegete a single right (authorizationRule)
    - _The API will support both deleting whole policies and individual rules_ 

Other questions:
- We need to decide whether or not we should create separate policy files per delegation, for each app-offeredby-coveredby tuple, or for each app-offeredby-coveredby-delegatedby tuple.
    - _One policy per {app,offeredBy,coveredBy}-tuple_
- How do we handle history? Can blob versioning help us? What should be stored in 2.0?
    - _All edits to policies cause an insert into the database having the versionId for the blob. 2.0 will store DelegationEvents as normal in order to support "Aktivitetslogg"_ 
- Does storage accounts have sufficiently low latency in order for the PDP to perform well with lots of delegations?
    - _Initial benchmarks suggests yes_ 
- What are the (dis)advantages associated  with storing the polcies directly in Cosmos?
    - _Blob storage grants versioning which allows for simpler data-models_
- The proposal does not include editing existing policies (via PUT), but instead opts for changes being performed as deletions/inserts. This aligns with how the delegation-UI in Altinn2 portal works today. Will this cause problems / unreasonable limitations? Can we introduce PUT at a later stage without too much pain?
    - _It will be possible to add new rules to existing policies and delete individual rules. This will grant asufficient editing capability_
- The proposal does not include listing of "roletyperights". This is potentially solved by 2.0 PAP calling the "roleswithaccess" endpoint (which will need to be expanded to include actions granted to a role), and comparing that to the relevant rolelist (including inheritance)
- How are we to support today's DELETE /{who}/Delegations/{receiverId}/rights/{authzRuleId} for 3.0 apps?
    - _The APi allows for deletion of individual rules_

**Comment by TheTechArch** [comment]
Implemented and in production
